from sys import argv
script,filename = argv

print(f"We will now erase {filename}.")
print("If you don't want that hit CTRL-C(^c).")
print("If you want that then hit Enter.\n")
input(">>>")
print("Opening the file...")
target = open(filename,'w')
print("Truncating the file. Goodbye :') .")
target.truncate()
print("Gimme three lines")
lineOne = input("Line one:")
lineTwo = input("Line two:")
lineThree = input("Line three:")
print("These will now be written in the file...")
target.write(lineOne)
target.write("\n")
target.write(lineTwo)
target.write("\n")
target.write(lineThree)
target.write("\n")
print("Now lets close that damn file...")
target.close()
